name: Update Requirements.txt

on:
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'
  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        run: pipx install poetry==1.8.2
          
      - name: Export requirements.txt
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes
          
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add requirements.txt
          git commit -m "Update requirements.txt" || echo "No changes to commit"
          git push